/*******************************************************************************
 * Copyright (c) 2015 Bosch Software Innovations GmbH and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v1.0 which accompany this distribution.
 *  
 * The Eclipse Public License is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * The Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *  
 * Contributors:
 * Bosch Software Innovations GmbH - Please refer to git log
 *******************************************************************************/

package org.eclipse.vorto.codegen.tests.wizard.util

class FilledTestTemplate {
		public def String printTribleQuotationMarks() {
		return "'''";
	}

	public def String printEntryArrows() {
		return "«";
	}

	public def String printExitArrows() {
		return "»";
	}

	public def String print() {
		return '''
		package testPackageName

		import org.eclipse.core.runtime.IProgressMonitor
		import org.eclipse.vorto.codegen.api.ICodeGenerator
		import org.eclipse.vorto.codegen.api.tasks.Generated
		import org.eclipse.vorto.codegen.api.tasks.ICodeGeneratorTask
		import org.eclipse.vorto.codegen.api.tasks.IOutputter
		import org.eclipse.vorto.codegen.api.tasks.eclipse.EclipseProjectGenerator
		import org.eclipse.vorto.core.api.model.informationmodel.InformationModel
		
		class testGeneratorName implements ICodeGenerator<InformationModel> {
		
			override generate(InformationModel infomodel, IProgressMonitor monitor) {
				new EclipseProjectGenerator(infomodel.getName()+"Device").addTask(new EmptyJavaGeneratorTask()).javaNature().generate(infomodel,monitor);
			}
			
			public static class EmptyJavaGeneratorTask implements ICodeGeneratorTask<InformationModel> {
				public override generate(InformationModel infomodel, IOutputter outputter) {
			    	outputter.output(new Generated(infomodel.getName(),null, getContent));
			    }
			    def String getContent() {
			   		return '//Generated by testGeneratorName';
			    }
			}
			
			override getName() {
				return "testGeneratorName";
			}
		}
		'''
	}}