/**
 * Copyright (c) 2018 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.vorto.repository.core.impl;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.vorto.repository.core.IModelRepository;
import org.eclipse.vorto.repository.core.IRepositoryManager;
import org.eclipse.vorto.repository.core.IUserContext;
import org.eclipse.vorto.repository.core.ModelInfo;
import org.eclipse.vorto.repository.core.events.AppEvent;
import org.eclipse.vorto.repository.core.events.EventType;
import org.eclipse.vorto.repository.domain.User;
import org.eclipse.vorto.repository.domain.UserRole;
import org.eclipse.vorto.repository.search.ISearchService;
import org.eclipse.vorto.repository.tenant.ITenantService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationListener;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.stereotype.Component;

/**
 * The purpose of this class is to listen to EVENTS generated by other components for which an
 * action should be done on the repository
 * 
 *
 */

@Component
public class ModelRepositoryEventListener implements ApplicationListener<AppEvent> {
  
  private static final String USER_ADMIN = "Admin";

  @Autowired
  private ModelRepositoryFactory repositoryFactory;
  
  @Autowired
  private ISearchService searchService;
  
  @Override
  public void onApplicationEvent(AppEvent event) {
    if (event.getEventType() == EventType.USER_DELETED) {
      makeModelsAnonymous(event);
    } else if (event.getEventType() == EventType.TENANT_ADDED) {
      createWorkspaceForTenant(event);
    } else if (event.getEventType() == EventType.TENANT_DELETED) {
      deleteWorkspaceForTenant(event);
    }
  }

  private void deleteWorkspaceForTenant(AppEvent event) {
    IUserContext userContext = event.getUserContext();
    IRepositoryManager repoMgr = repositoryFactory.getRepositoryManager(userContext.getTenant(), 
        userContext.getAuthentication());
    repoMgr.removeTenantWorkspace(userContext.getTenant());
  }

  private void createWorkspaceForTenant(AppEvent event) {
    IUserContext userContext = event.getUserContext();
    IRepositoryManager repoMgr = repositoryFactory.getRepositoryManager(userContext.getTenant(), 
        userContext.getAuthentication());
    repoMgr.createTenantWorkspace(userContext.getTenant());
  }

  private void makeModelsAnonymous(AppEvent event) {
    String username = (String) event.getSubject();
    
    IUserContext technicalUserContext = UserContext.user(createAdminTechnicalUser());
    
    List<ModelInfo> result = searchService.search("author:" + username, technicalUserContext);
    result.forEach(model -> {
      IModelRepository repository = repositoryFactory.getRepositoryByModel(model.getId(), technicalUserContext);
      model.setAuthor(User.USER_ANONYMOUS);
      repository.updateMeta(model);
    });
  }
  
  private Authentication createAdminTechnicalUser() {
    List<GrantedAuthority> authorities = new ArrayList<GrantedAuthority>();
    authorities.add(new SimpleGrantedAuthority(UserRole.ROLE_SYS_ADMIN));
    return new UsernamePasswordAuthenticationToken(USER_ADMIN, USER_ADMIN, authorities);
  }

  public ModelRepositoryFactory getRepositoryFactory() {
    return repositoryFactory;
  }

  public void setRepositoryFactory(ModelRepositoryFactory repositoryFactory) {
    this.repositoryFactory = repositoryFactory;
  }

  public ISearchService getSearchService() {
    return searchService;
  }

  public void setSearchService(ISearchService searchService) {
    this.searchService = searchService;
  }
}
