/*******************************************************************************
 *  Copyright (c) 2015 Bosch Software Innovations GmbH and others.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  and Eclipse Distribution License v1.0 which accompany this distribution.
 *   
 *  The Eclipse Public License is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *  The Eclipse Distribution License is available at
 *  http://www.eclipse.org/org/documents/edl-v10.php.
 *   
 *  Contributors:
 *  Bosch Software Innovations GmbH - Please refer to git log
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.eclipse.vorto.editor.infomodel;

import org.eclipse.vorto.editor.EclipseFileSystemAccessOutputter;
import org.eclipse.vorto.editor.infomodel.generator.InformationModelOutputConfigurationProvider;
import org.eclipse.vorto.editor.infomodel.scoping.InformationModelScopeProvider;
import org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.scoping.IScopeProvider;

import com.google.inject.Binder;
import com.google.inject.Provides;
import com.google.inject.Singleton;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class InformationModelRuntimeModule
		extends
		org.eclipse.vorto.editor.infomodel.AbstractInformationModelRuntimeModule {

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(IOutputConfigurationProvider.class)
				.to(InformationModelOutputConfigurationProvider.class)
				.in(Singleton.class);
	}

	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return InformationModelScopeProvider.class;
	}

	@Provides
	public EclipseResourceFileSystemAccess2 getFileSystemAccess() {
		return new EclipseFileSystemAccessOutputter();
	}

	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return QualifiedNameWithVersionProvider.class;
	}
}
