version: '3'
services:
  repository:
    depends_on:
      - "db"
    image: eclipsevorto/vorto-repo
    volumes:
      - ~/.vorto:/root/.vorto
    ports:
      - "8080:8080"
    env_file:
      - docker/vorto-variables.env
    networks:
      - backend
  db:
    volumes:
       - /opt/mysql_data:/var/lib/mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - docker/vorto-variables.env
    networks:
      - backend
networks:
  backend:
    driver: bridge
