version: '3'
services:
  repository:
    depends_on:
      - "db"
    image: eclipsevorto/vorto-repo:nightly
    volumes:
      - ~/.vorto:/root/.vorto
    ports:
      - "8080:8080"
    env_file:
      - docker/vorto-variables.env
    networks:
      - backend
  generators:
    depends_on:
      - "repository"
    image: eclipsevorto/vorto-generators:nightly
    volumes:
      - ./docker/config/generators/:/code/config
    env_file:
      - docker/vorto-variables.env
    networks:
      - backend
  3rd-party-generators:
    depends_on:
      - "repository"
    image: eclipsevorto/vorto-generators-3rd-party:nightly
    volumes:
      - ./docker/config/3rd-party-generators/:/code/config
    env_file:
      - docker/vorto-variables.env
    networks:
      - backend
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - docker/vorto-variables.env
    networks:
      - backend
networks:
  backend:
    driver: bridge
