version: '3'
services:
  repository:
    depends_on:
      - "db"
    image: eclipsevorto/vorto-repo:nigthly
    ports:
      - "8080:8080"
    env_file:
      - docker/vorto-variables.env
    networks:
      - backend
  generators:
    depends_on:
      - "repository"
    image: eclipsevorto/vorto-generators:nigthly
    env_file:
      - docker/vorto-variables.env
    networks:
      - backend
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - docker/vorto-variables.env
    networks:
      - backend
networks:
  backend:
    driver: bridge
