<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mapping" nsURI="http://www.eclipse.org/vorto/metamodel/Mapping"
    nsPrefix="mapping">
  <eClassifiers xsi:type="ecore:EClass" name="MappingModel" eSuperTypes="Model.ecore#//Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingType" eType="#//MappingType"
        containment="true"/>
  </eClassifiers>
<eClassifiers xsi:type="ecore:EClass" name="MappingType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfoModelMapping" eSuperTypes="#//MappingType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="infoModelMappingRules"
        upperBound="-1" eType="#//InfoModelMappingRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfoModelMappingRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="infoModelSourceElements"
        upperBound="-1" eType="#//InfoModelSourceElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//InfoModelTargetElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfoModelTargetElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfoModelSourceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="infoModel" eType="ecore:EClass platform:/resource/org.eclipse.vorto.core/model/InformationModel.ecore#//InformationModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="infoModelChild" eType="#//InfoModelChild"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfoModelChild"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfoModelFbElement" eSuperTypes="#//InfoModelChild">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionblock" eType="ecore:EClass platform:/resource/org.eclipse.vorto.core/model/InformationModel.ecore#//FunctionblockProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InformationModelProperty" eSuperTypes="#//InfoModelChild">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="#//InfoModelAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InfoModelAttribute">
    <eLiterals name="name" literal="name"/>
    <eLiterals name="namespace" value="1" literal="namespace"/>
    <eLiterals name="version" value="2" literal="version"/>
    <eLiterals name="displayname" value="3" literal="displayname"/>
    <eLiterals name="category" value="4" literal="category"/>
    <eLiterals name="description" value="5" literal="description"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockMapping" eSuperTypes="#//MappingType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionBlockMappingRules"
        upperBound="-1" eType="#//FunctionBlockMappingRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockMappingRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionBlockSourceElements"
        upperBound="-1" eType="#//FunctionBlockSourceElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//FunctionBlockTargetElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockTargetElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockSourceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionblock" eType="ecore:EClass platform:/resource/org.eclipse.vorto.core/model/Functionblock.ecore#//FunctionblockModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionBlockElement" eType="#//FunctionBlockElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockElementAttribute" eSuperTypes="#//FunctionBlockElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="#//FunctionblockModelAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockChildElement" eSuperTypes="#//FunctionBlockElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//OperationElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="#//FBTypeElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="ecore:EClass platform:/resource/org.eclipse.vorto.core/model/Functionblock.ecore#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationElement" eSuperTypes="#//FunctionBlockChildElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatusElement" eSuperTypes="#//FunctionBlockChildElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaultElement" eSuperTypes="#//FunctionBlockChildElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventElement" eSuperTypes="#//FunctionBlockChildElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="ecore:EClass platform:/resource/org.eclipse.vorto.core/model/Functionblock.ecore#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBTypeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="ecore:EClass platform:/resource/org.eclipse.vorto.core/model/Datatype.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FunctionblockModelAttribute">
    <eLiterals name="name" literal="name"/>
    <eLiterals name="namespace" value="1" literal="namespace"/>
    <eLiterals name="version" value="2" literal="version"/>
    <eLiterals name="displayname" value="3" literal="displayname"/>
    <eLiterals name="category" value="4" literal="category"/>
    <eLiterals name="description" value="5" literal="description"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityMapping" eSuperTypes="#//DataTypeMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityMappingRules" upperBound="-1"
        eType="#//EntityMappingRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityMappingRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityMappingElements"
        upperBound="-1" eType="#//EntitySourceElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EntitySourceElement" upperBound="-1"
        eType="#//EntitySourceElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetElement" eType="#//EntityTargetElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityTargetElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntitySourceElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntityPropertyElement" eSuperTypes="#//EntitySourceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="ecore:EClass platform:/resource/org.eclipse.vorto.core/model/Datatype.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="#//ModelAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityExpressionRef" eSuperTypes="#//EntitySourceElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumMapping" eSuperTypes="#//DataTypeMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumMappingRules" upperBound="-1"
        eType="#//EnumMappingRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumMappingRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumElements" upperBound="-1"
        eType="#//EnumSourceElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EnumSourceElement" upperBound="-1"
        eType="#//EnumSourceElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetElement" eType="#//EnumTargetElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumTargetElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumSourceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="ecore:EClass platform:/resource/org.eclipse.vorto.core/model/Datatype.ecore#//Enum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumPropertyElement" eSuperTypes="#//EnumSourceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="#//ModelAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumExpression" eSuperTypes="#//EnumSourceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" eType="ecore:EClass platform:/resource/org.eclipse.vorto.core/model/Datatype.ecore#//EnumLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumReference" eSuperTypes="#//EnumTargetElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//EnumMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockReference" eSuperTypes="#//InfoModelTargetElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//FunctionBlockMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeReference" eSuperTypes="#//FunctionBlockTargetElement #//EntityTargetElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//DataTypeMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeMapping" eSuperTypes="#//MappingType"/>
  <eClassifiers xsi:type="ecore:EClass" name="StereoTypeReference" eSuperTypes="#//InfoModelTargetElement #//FunctionBlockTargetElement #//EntityTargetElement #//EnumTargetElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetElement" eType="#//StereoTypeElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StereoTypeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereoTypes" upperBound="-1"
        eType="#//StereoType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StereoType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModelAttribute">
    <eLiterals name="name" literal="name"/>
    <eLiterals name="namespace" value="1" literal="namespace"/>
    <eLiterals name="description" value="2" literal="version"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedEntityExpression" eSuperTypes="#//EntityExpressionRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//EntityExpressionRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" eType="ecore:EClass platform:/resource/org.eclipse.vorto.core/model/Datatype.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityExpression" eSuperTypes="#//EntityExpressionRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="ecore:EClass platform:/resource/org.eclipse.vorto.core/model/Datatype.ecore#//Entity"/>
  </eClassifiers>
</ecore:EPackage>