<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2020 Contributors to the Eclipse Foundation

    See the NOTICE file(s) distributed with this work for additional
    information regarding copyright ownership.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License 2.0 which is available at
    https://www.eclipse.org/legal/epl-2.0

    SPDX-License-Identifier: EPL-2.0

-->
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="informationmodel" nsURI="http://www.eclipse.org/vorto/metamodel/InformationModel"
    nsPrefix="informationmodel">
  <eClassifiers xsi:type="ecore:EClass" name="InformationModel" eSuperTypes="Model.ecore#//Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//FunctionblockProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionblockProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass Functionblock.ecore#//FunctionblockModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presence" eType="ecore:EClass Datatype.ecore#//Presence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  	 <eStructuralFeatures xsi:type="ecore:EReference" name="extendedFunctionBlock"
        eType="ecore:EClass Functionblock.ecore#//FunctionBlock" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
