/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.vorto.editor.infomodel.tests

import com.google.inject.Inject
import org.eclipse.vorto.core.api.model.informationmodel.InformationModel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(InformationModelInjectorProvider)
class InformationModelParsingTest{

	@Inject
	ParseHelper<InformationModel> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
