# // Generated by Vorto from org.eclipse.vorto.ConfigPropertiesFunctionBlock

class ConfigPropertiesFunctionBlock(object):
    def __init__(self):
        self.configValue = 0.0
        self.configBoolean = 0.0

    ### Configuration property configValue
    @property
    def configValue(self):
        return self.__configValue[0]
    
    @configValue.setter
    def configValue(self, value):
        self.__configValue = (value, True)
    
    ### Configuration property configBoolean
    @property
    def configBoolean(self):
        return self.__configBoolean[0]
    
    @configBoolean.setter
    def configBoolean(self, value):
        self.__configBoolean = (value, True)
    
    def serializeStatus(self, serializer):
        pass
    def serializeConfiguration(self, serializer):
        serializer.first_prop = True
        if self.__configValue[1]:
               serializer.serialize_property("configValue", self.__configValue[0])
               self.__configValue = (self.__configValue[0], False)
        if self.__configBoolean[1]:
               serializer.serialize_property("configBoolean", self.__configBoolean[0])
               self.__configBoolean = (self.__configBoolean[0], False)
