# // Generated by Vorto from org.eclipse.vorto.StatusPropertiesFunctionBlock

class StatusPropertiesFunctionBlock(object):
    def __init__(self):
        self.statusValue = 0.0
        self.statusBoolean = 0.0

    ### Status property statusValue
    @property
    def statusValue(self):
        return self.__statusValue[0]
    
    @statusValue.setter
    def statusValue(self, value):
        self.__statusValue = (value, True)
    
    ### Status property statusBoolean
    @property
    def statusBoolean(self):
        return self.__statusBoolean[0]
    
    @statusBoolean.setter
    def statusBoolean(self, value):
        self.__statusBoolean = (value, True)
    
    def serializeStatus(self, serializer):
        serializer.first_prop = True
        if self.__statusValue[1]:
               serializer.serialize_property("statusValue", self.__statusValue[0])
               self.__statusValue = (self.__statusValue[0], False)
        if self.__statusBoolean[1]:
               serializer.serialize_property("statusBoolean", self.__statusBoolean[0])
               self.__statusBoolean = (self.__statusBoolean[0], False)
    def serializeConfiguration(self, serializer):
        pass
