server:
  port: 8080
  contextPath: /infomodelrepository
  
spring:
  datasource:
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vorto
    username: <<database username>>
    password: <<database password>>
  jpa:
    show-sql: true
    generate-ddl: true
  hibernate:
    ddl-auto: validate

logging:
  level:
    org.springframework: INFO
    
mail:
  smtp:
    host: localhost
    port: 25
  from: vorto-dev@eclipse.org
