/*
 * generated by Xtext 2.10.0
 */
package org.system.model


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AggregateStandaloneSetup extends AggregateStandaloneSetupGenerated {

	def static void doSetup() {
		new AggregateStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
