spring:
  jpa:
    show-sql: false
    generate-ddl: true
  hibernate:
    ddl-auto: validate

logging:
  level:
    org.springframework: INFO
    
mail:
  smtp:
    host: localhost
    port: 25
  from: vorto-dev@eclipse.org
