server:
  contextPath: /

repo:
  configFile: vorto-repository-config-mysql.json

spring:
  datasource:
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    wait_timeout: 180
    validationInterval: 60    
    validationQuery: SELECT 1
    driver-class-name:
    url:
    username:
    password:
  jpa:
    show-sql: false
    generate-ddl: true
  hibernate:
    ddl-auto: validate
