repo:
  configFile: vorto-repository-config-file.json
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:${user.home}/.vorto

server:
  port: 8080
  contextPath: /
  use-forward-headers: true
  admin: aedelmann

eidp_clientid: 123
eidp_secret: 123

plugins : "W3sia2V5IiA6ICJib3NjaGlvdHN1aXRlIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwczovL2l5bm8zbXp4MWguZXhlY3V0ZS1hcGkuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vRGV2ZWxvcG1lbnQifSwKCQkJeyJrZXkiIDogImVjbGlwc2VkaXR0byIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cHM6Ly9peW5vM216eDFoLmV4ZWN1dGUtYXBpLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL0RldmVsb3BtZW50In0sCgkJICAgIHsia2V5IiA6ICJlY2xpcHNlaG9ubyIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cHM6Ly9peW5vM216eDFoLmV4ZWN1dGUtYXBpLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL0RldmVsb3BtZW50In0sCgkJICAgIHsia2V5IiA6ICJwcm90b2J1ZiIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cHM6Ly9peW5vM216eDFoLmV4ZWN1dGUtYXBpLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL0RldmVsb3BtZW50IiwidGFnIiA6ICJkZW1vIn0sCgkJICAgIHsia2V5IiA6ICJqc29uc2NoZW1hIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwczovL2l5bm8zbXp4MWguZXhlY3V0ZS1hcGkuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vRGV2ZWxvcG1lbnQiLCJ0YWciIDogImRlbW8ifSwKCQkgICAgeyJrZXkiIDogImF6dXJlIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwczovL2l5bm8zbXp4MWguZXhlY3V0ZS1hcGkuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vRGV2ZWxvcG1lbnQiLCJ0YWciIDogImRlbW8ifSwKIHsia2V5IiA6ICJvcGVuYXBpIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwczovL2l5bm8zbXp4MWguZXhlY3V0ZS1hcGkuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vRGV2ZWxvcG1lbnQifSwKCQkgICAgeyJrZXkiIDogImx3bTJtIiwgInBsdWdpblR5cGUiOiAiaW1wb3J0ZXIiLCAibmFtZSIgOiAiTHdNMk0iICwgImZpbGVUeXBlIiA6ICIueG1sIiwgImRlc2NyaXB0aW9uIiA6ICJDb252ZXJ0cyBMd00yTSBkZXNjcmlwdGlvbnMgdG8gVm9ydG8iLCAiZW5kcG9pbnQiIDogImh0dHBzOi8vaXlubzNtengxaC5leGVjdXRlLWFwaS5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbS9EZXZlbG9wbWVudCJ9XQ=="