server:
  port: 8080
  contextPath: /infomodelrepository
  use-forward-headers: true
  admin: aedelmann
  config:
    authenticatedSearchMode: false
    generatorUser: generator
    generatorPassword: 123
    
github:
  oauth2:
    enabled: true
    client:
      clientId: ${github_clientid}
      clientSecret: ${github_clientSecret}
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      scope:
         - user:email
    resource:
      userInfoUri: https://api.github.com/user
    
eidp:
  oauth2:
    enabled: false
    client:
      clientId: 123
      clientSecret: 123
      accessTokenUri: https://identity.bosch.com/connect/token
      userAuthorizationUri: https://accounts.bosch.com/adfs/oauth2/authorize
      clientAuthenticationScheme: form
      resource: https://vorto.eclipse.org
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://accounts.bosch.com/adfs/userinfo
      logoutRedirectUrl:
      preferTokenInfo: true

mail:
  smtp:
    host: localhost
    port: 25
    auth: false
  from: vorto-dev@eclipse.org
  login:
    username:
    password: 