spring:
  datasource:
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    wait_timeout: 180
    validationInterval: 60
    validationQuery: SELECT 1
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/vorto"
    username: root
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql

repo:
  configFile: vorto-repository-config-mysql.json

