server:
  host: vorto.eclipse.org
  contextPath: /
  config:
    generatorUser: ${generatorUser}
    generatorPassword: ${generatorPassword}

repo:
  configFile: vorto-repository-config-file.json

spring:
  profiles.active: eclipse
  config.location: config
  datasource:
    url: jdbc:mysql://${database:port}/vorto
    username: ${datasource_user_name}
    password: ${datasource_user_password}

