ALTER TABLE USER ADD COLUMN IF NOT EXISTS IS_TECHNICAL_USER BOOLEAN;
UPDATE USER SET AUTHENTICATION_PROVIDER = 'BOSCH_IOT_SUITE_AUTH' WHERE USERNAME LIKE 'S-%';
UPDATE USER SET IS_TECHNICAL_USER=TRUE WHERE AUTHENTICATION_PROVIDER = 'BOSCH_IOT_SUITE_AUTH';
UPDATE USER SET IS_TECHNICAL_USER=FALSE WHERE AUTHENTICATION_PROVIDER <> 'BOSCH_IOT_SUITE_AUTH';