# Site settings
title: Eclipse Vorto
email: vorto-dev@eclipse.org
description: Eclipse Vorto - IoT Toolset for standardized device descriptions
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://vorto.eclipse.org" # the base hostname & protocol for your site
twitter_username: VortoIoT
github_username:  vorto

# Build settings
markdown: kramdown
paginate: 3
paginate_path: '/blog/page:num/'

plugins: [jekyll-paginate]

