/**
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/*
*****************************************************************************************
* The present code has been generated by the Eclipse Vorto Code Generator.
*
* The basis for the generation was the Enum which is uniquely identified by:
* Name:			UnitEnum
* Namespace:	org.eclipse.vorto
* Version:		1.0.0
*****************************************************************************************
*/

package device.mysensor.model.datatypes;

/**
* 
*/
public enum UnitEnum {
	/**
	* 
	*/
	KG,
	
	/**
	* 
	*/
	G
	
}
