/**
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/*
*****************************************************************************************
* The present code has been generated by the Eclipse Vorto Code Generator.
*
* The basis for the generation was the Entity which is uniquely identified by:
* Name:			UnitEntity
* Namespace:	org.eclipse.vorto
* Version:		1.0.0
*****************************************************************************************
*/

package device.mysensor.model.datatypes;

/**
* 
*/
public class UnitEntity {

	/**
	* 
	*/
	private float value;
	
	/**
	* 
	*/
	private UnitEnum unitEnum;
	
	/**
	* Getter for value.
	*/
	public float getValue() {
		return this.value;
	}
	
	/**
	* Setter for value.
	*/
	public void setValue(float value) {
		this.value = value;
	}
	
	/**
	* Getter for unitEnum.
	*/
	public UnitEnum getUnitEnum() {
		return this.unitEnum;
	}
	
	/**
	* Setter for unitEnum.
	*/
	public void setUnitEnum(UnitEnum unitEnum) {
		this.unitEnum = unitEnum;
	}
	
}
