/*
*****************************************************************************************
* The present code has been generated by the Eclipse Vorto Code Generator.
*
* The basis for the generation was the Enum which is uniquely identified by:
* Name:			UnitEnum
* Namespace:	org.eclipse.vorto
* Version:		1.0.0
*****************************************************************************************
*/

package device.mysensor.model.datatypes;

/**
* 
*/
public enum UnitEnum {
	/**
	* 
	*/
	KG,
	
	/**
	* 
	*/
	G
	
}
