/*
*****************************************************************************************
* The present code has been generated by the Eclipse Vorto Code Generator.
*
* The basis for the generation was the Entity which is uniquely identified by:
* Name:			UnitEntity
* Namespace:	org.eclipse.vorto
* Version:		1.0.0
*****************************************************************************************
*/

package device.mysensor.model.datatypes;

/**
* 
*/
public class UnitEntity {

	/**
	* 
	*/
	private float value;
	
	/**
	* 
	*/
	private UnitEnum unitEnum;
	
	/**
	* Getter for value.
	*/
	public float getValue() {
		return this.value;
	}
	
	/**
	* Setter for value.
	*/
	public void setValue(float value) {
		this.value = value;
	}
	
	/**
	* Getter for unitEnum.
	*/
	public UnitEnum getUnitEnum() {
		return this.unitEnum;
	}
	
	/**
	* Setter for unitEnum.
	*/
	public void setUnitEnum(UnitEnum unitEnum) {
		this.unitEnum = unitEnum;
	}
	
}
