/*
 * generated by Xtext 2.9.0
 */
package org.eclipse.vorto.editor.infomodel.web

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
class InformationModelWebModule extends AbstractInformationModelWebModule {
}
